---
version: "3.8"

services:
  portainer:
    container_name: portainer-ce
    image: portainer/portainer-ce:alpine
    command: -H unix:///var/run/docker.sock
    restart: always
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'localhost:9000']
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    networks:
      - traefik-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    labels:
      # Frontend
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      - traefik.http.routers.portainer-web.rule=Host(`portainer.domain.tld`)
      - traefik.http.routers.portainer-web.entrypoints=websecure
      - traefik.http.services.portainer-web.loadbalancer.server.port=9000
      - traefik.http.routers.portainer-web.service=portainer-web

      # Edge
      - traefik.http.routers.portainer-edge.rule=Host(`edge.domain.tld`)
      - traefik.http.routers.portainer-edge.entrypoints=websecure
      - traefik.http.services.portainer-edge.loadbalancer.server.port=8000
      - traefik.http.routers.portainer-edge.service=portainer-edge

networks:
  traefik-proxy:
    external: true

volumes:
  data:
