---
version: "3.8"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - WEBUI_PORT=80
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 8192M
    ports:
      - 6881:6881
      - 6881:6881/udp
    networks:
      - traefik-proxy
    volumes:
      - config:/config
      - /mnt/X/Y:/Y
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      - traefik.http.routers.qbittorrent.rule=Host(`torrent.domain.tld`)
      - traefik.http.routers.qbittorrent.entrypoints=websecure
      - traefik.http.services.qbittorrent.loadbalancer.server.port=80
      - traefik.http.routers.qbittorrent.service=qbittorrent

networks:
  traefik-proxy:
    external: true
volumes:
  config:
