---
version: "3.8"

services:
  unbound:
    container_name: unbound
    image: klutchell/unbound:latest
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'dig', '-p', '53', 'dnssec.works', '@127.0.0.1']
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    networks:
      - dns
    volumes:
      - ./dot.conf:/etc/unbound/custom.conf.d/dot.conf

networks:
  dns:
    external: true
