# Dynamic configuration
http:
  middlewares:
    nofloc:
      headers:
        customResponseHeaders:
          Permissions-Policy: "interest-cohort=()"

    xframedeny:  
      headers:
        frameDeny: true

    secureHeaders:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: false
        stsSeconds: 31536000   

    bw-stripPrefix:
      stripPrefix:
        prefixes:
          - "/notifications/hub"
        forceSlash: false

    # we use this on the dashboard to authenticate
    user-auth:
      basicAuth:
        users:
          - "admin:$password_hash"

    nextcloud-header:
      headers:
        referrerPolicy: "no-referrer"
        contentTypeNosniff: true
        customFrameOptionsValue: "SAMEORIGIN"
        customRequestHeaders:
          X-Forwarded-Proto: https
        customResponseHeaders:
          X-Robots-Tag: "none"

tls:
  options:
    default:
      minVersion: VersionTLS13
