version: '3.7'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    environment:
      - DESEC_TOKEN=YOUR_DESEC_TOKEN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Provide read-only access to docker engine for traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount file with static traefik configuration
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      # Add file with dynamic configuration yml
      - ./config/dynamic.yml:/etc/traefik/config/dynamic.yml
      # Add folder with ACME account data
      - ./storage/acme.json:/etc/traefik/storage/acme.json
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`APP_HOSTNAME.tld`)"
      - "traefik.http.routers.traefik-secure.middlewares=user-auth@file,nofloc@file,xframedeny@file"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  proxy:
    external: true
