---
version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: GENERATE_DB_ROOT_PW
      MYSQL_DATABASE: DB_NAME
      MYSQL_USER: DB_USER_NAME
      MYSQL_PASSWORD: GENERATE_DB_USER_PW
    networks:
      - default
    volumes:
      - nextcloud-db-data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always
    networks:
      - default
    volumes:
      - nextcloud-redis-data:/var/lib/redis

  app:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-app
    restart: always
    environment:
      REDIS_HOST: redis
      MYSQL_HOST: db:3306
      MYSQL_DATABASE: DB_NAME
      MYSQL_USER: DB_USER_NAME
      MYSQL_PASSWORD: GENERATE_DB_USER_PW
      TRUSTED_PROXIES: DOCKER_PROXY_NETWORK_SEGMENT_ADDRESSES
      OVERWRITEHOST: APP_HOSTNAME.tld
      OVERWRITEPROTOCOL: https
    depends_on:
      - db
      - redis
    networks:
      - default
    volumes:
      - nextcloud-app-data:/var/www/html

  web:
    image: nginx:alpine
    container_name: nextcloud-web
    restart: always
    depends_on:
      - app
    networks:
      - proxy
      - default
    volumes:
      - nextcloud-app-data:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`APP_HOSTNAME.tld`)"
      - "traefik.http.routers.nextcloud.service=nextcloud"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-header@file,nextcloud-dav@docker,nextcloud-well-known@docker"
      - "traefik.http.middlewares.nextcloud-dav.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud-dav.redirectregex.regex=https?://([^/]*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-dav.redirectregex.replacement=https://$${1}/remote.php/dav/"
      - "traefik.http.middlewares.nextcloud-well-known.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud-well-known.redirectregex.regex=https?://([^/]*)(/.well-known[^#]*)"
      - "traefik.http.middlewares.nextcloud-well-known.redirectregex.replacement=https://$${1}/index.php$${2}"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

networks:
  proxy:
    external: true

volumes:
  nextcloud-app-data:
    name: nextcloud-app-data
  nextcloud-db-data:
    name: nextcloud-db-data
  nextcloud-redis-data:
    name: nextcloud-redis-data
